// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MdmUIClient is the client API for MdmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MdmUIClient interface {
	// ListDeviceSpecs returns a list of Storage Device(s) that can be started through the UI.
	ListDeviceSpecs(ctx context.Context, in *ListDeviceSpecsRequest, opts ...grpc.CallOption) (MdmUI_ListDeviceSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type mdmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewMdmUIClient(cc grpc.ClientConnInterface) MdmUIClient {
	return &mdmUIClient{cc}
}

func (c *mdmUIClient) ListDeviceSpecs(ctx context.Context, in *ListDeviceSpecsRequest, opts ...grpc.CallOption) (MdmUI_ListDeviceSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MdmUI_ServiceDesc.Streams[0], "/v1.MdmUI/ListDeviceSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &mdmUIListDeviceSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MdmUI_ListDeviceSpecsClient interface {
	Recv() (*ListDeviceSpecsResponse, error)
	grpc.ClientStream
}

type mdmUIListDeviceSpecsClient struct {
	grpc.ClientStream
}

func (x *mdmUIListDeviceSpecsClient) Recv() (*ListDeviceSpecsResponse, error) {
	m := new(ListDeviceSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mdmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.MdmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MdmUIServer is the server API for MdmUI service.
// All implementations must embed UnimplementedMdmUIServer
// for forward compatibility
type MdmUIServer interface {
	// ListDeviceSpecs returns a list of Storage Device(s) that can be started through the UI.
	ListDeviceSpecs(*ListDeviceSpecsRequest, MdmUI_ListDeviceSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedMdmUIServer()
}

// UnimplementedMdmUIServer must be embedded to have forward compatible implementations.
type UnimplementedMdmUIServer struct {
}

func (UnimplementedMdmUIServer) ListDeviceSpecs(*ListDeviceSpecsRequest, MdmUI_ListDeviceSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDeviceSpecs not implemented")
}
func (UnimplementedMdmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedMdmUIServer) mustEmbedUnimplementedMdmUIServer() {}

// UnsafeMdmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MdmUIServer will
// result in compilation errors.
type UnsafeMdmUIServer interface {
	mustEmbedUnimplementedMdmUIServer()
}

func RegisterMdmUIServer(s grpc.ServiceRegistrar, srv MdmUIServer) {
	s.RegisterService(&MdmUI_ServiceDesc, srv)
}

func _MdmUI_ListDeviceSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDeviceSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MdmUIServer).ListDeviceSpecs(m, &mdmUIListDeviceSpecsServer{stream})
}

type MdmUI_ListDeviceSpecsServer interface {
	Send(*ListDeviceSpecsResponse) error
	grpc.ServerStream
}

type mdmUIListDeviceSpecsServer struct {
	grpc.ServerStream
}

func (x *mdmUIListDeviceSpecsServer) Send(m *ListDeviceSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MdmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MdmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MdmUI_ServiceDesc is the grpc.ServiceDesc for MdmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MdmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MdmUI",
	HandlerType: (*MdmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _MdmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDeviceSpecs",
			Handler:       _MdmUI_ListDeviceSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdm-ui.proto",
}
