// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SdmServiceClient is the client API for SdmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SdmServiceClient interface {
	// StartLocalDevice starts a Storage Device on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the sdm/config.yaml
	//   3. all bytes constituting the Device YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDevice(ctx context.Context, opts ...grpc.CallOption) (SdmService_StartLocalDeviceClient, error)
	// StartFromPreviousDevice starts a new Storage Device based on a previous one.
	// If the previous Storage Device does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDevice(ctx context.Context, in *StartFromPreviousDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error)
	// StartDeviceRequest starts a new Storage Device based on its specification.
	StartDevice(ctx context.Context, in *StartDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error)
	// Searches for Storage Device(s) known to this instance
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// Subscribe listens to new Storage Device(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SdmService_SubscribeClient, error)
	// GetDevice retrieves details of a single Storage Device
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	// Listen listens to Storage Device updates and log output of a running Storage Device
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (SdmService_ListenClient, error)
	// StopDevice stops a currently running Storage Device
	StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*StopDeviceResponse, error)
}

type sdmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSdmServiceClient(cc grpc.ClientConnInterface) SdmServiceClient {
	return &sdmServiceClient{cc}
}

func (c *sdmServiceClient) StartLocalDevice(ctx context.Context, opts ...grpc.CallOption) (SdmService_StartLocalDeviceClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdmService_ServiceDesc.Streams[0], "/v1.SdmService/StartLocalDevice", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdmServiceStartLocalDeviceClient{stream}
	return x, nil
}

type SdmService_StartLocalDeviceClient interface {
	Send(*StartLocalDeviceRequest) error
	CloseAndRecv() (*StartDeviceResponse, error)
	grpc.ClientStream
}

type sdmServiceStartLocalDeviceClient struct {
	grpc.ClientStream
}

func (x *sdmServiceStartLocalDeviceClient) Send(m *StartLocalDeviceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sdmServiceStartLocalDeviceClient) CloseAndRecv() (*StartDeviceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartDeviceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdmServiceClient) StartFromPreviousDevice(ctx context.Context, in *StartFromPreviousDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error) {
	out := new(StartDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.SdmService/StartFromPreviousDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdmServiceClient) StartDevice(ctx context.Context, in *StartDeviceRequest, opts ...grpc.CallOption) (*StartDeviceResponse, error) {
	out := new(StartDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.SdmService/StartDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdmServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, "/v1.SdmService/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdmServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SdmService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdmService_ServiceDesc.Streams[1], "/v1.SdmService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdmServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SdmService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type sdmServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *sdmServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdmServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.SdmService/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdmServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (SdmService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdmService_ServiceDesc.Streams[2], "/v1.SdmService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdmServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SdmService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type sdmServiceListenClient struct {
	grpc.ClientStream
}

func (x *sdmServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdmServiceClient) StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*StopDeviceResponse, error) {
	out := new(StopDeviceResponse)
	err := c.cc.Invoke(ctx, "/v1.SdmService/StopDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdmServiceServer is the server API for SdmService service.
// All implementations must embed UnimplementedSdmServiceServer
// for forward compatibility
type SdmServiceServer interface {
	// StartLocalDevice starts a Storage Device on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the sdm/config.yaml
	//   3. all bytes constituting the Device YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalDevice(SdmService_StartLocalDeviceServer) error
	// StartFromPreviousDevice starts a new Storage Device based on a previous one.
	// If the previous Storage Device does not have the can-replay condition set this call will result in an error.
	StartFromPreviousDevice(context.Context, *StartFromPreviousDeviceRequest) (*StartDeviceResponse, error)
	// StartDeviceRequest starts a new Storage Device based on its specification.
	StartDevice(context.Context, *StartDeviceRequest) (*StartDeviceResponse, error)
	// Searches for Storage Device(s) known to this instance
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// Subscribe listens to new Storage Device(s) updates
	Subscribe(*SubscribeRequest, SdmService_SubscribeServer) error
	// GetDevice retrieves details of a single Storage Device
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	// Listen listens to Storage Device updates and log output of a running Storage Device
	Listen(*ListenRequest, SdmService_ListenServer) error
	// StopDevice stops a currently running Storage Device
	StopDevice(context.Context, *StopDeviceRequest) (*StopDeviceResponse, error)
	mustEmbedUnimplementedSdmServiceServer()
}

// UnimplementedSdmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSdmServiceServer struct {
}

func (UnimplementedSdmServiceServer) StartLocalDevice(SdmService_StartLocalDeviceServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalDevice not implemented")
}
func (UnimplementedSdmServiceServer) StartFromPreviousDevice(context.Context, *StartFromPreviousDeviceRequest) (*StartDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousDevice not implemented")
}
func (UnimplementedSdmServiceServer) StartDevice(context.Context, *StartDeviceRequest) (*StartDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDevice not implemented")
}
func (UnimplementedSdmServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedSdmServiceServer) Subscribe(*SubscribeRequest, SdmService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSdmServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedSdmServiceServer) Listen(*ListenRequest, SdmService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedSdmServiceServer) StopDevice(context.Context, *StopDeviceRequest) (*StopDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDevice not implemented")
}
func (UnimplementedSdmServiceServer) mustEmbedUnimplementedSdmServiceServer() {}

// UnsafeSdmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SdmServiceServer will
// result in compilation errors.
type UnsafeSdmServiceServer interface {
	mustEmbedUnimplementedSdmServiceServer()
}

func RegisterSdmServiceServer(s grpc.ServiceRegistrar, srv SdmServiceServer) {
	s.RegisterService(&SdmService_ServiceDesc, srv)
}

func _SdmService_StartLocalDevice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SdmServiceServer).StartLocalDevice(&sdmServiceStartLocalDeviceServer{stream})
}

type SdmService_StartLocalDeviceServer interface {
	SendAndClose(*StartDeviceResponse) error
	Recv() (*StartLocalDeviceRequest, error)
	grpc.ServerStream
}

type sdmServiceStartLocalDeviceServer struct {
	grpc.ServerStream
}

func (x *sdmServiceStartLocalDeviceServer) SendAndClose(m *StartDeviceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sdmServiceStartLocalDeviceServer) Recv() (*StartLocalDeviceRequest, error) {
	m := new(StartLocalDeviceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SdmService_StartFromPreviousDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdmServiceServer).StartFromPreviousDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdmService/StartFromPreviousDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdmServiceServer).StartFromPreviousDevice(ctx, req.(*StartFromPreviousDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdmService_StartDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdmServiceServer).StartDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdmService/StartDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdmServiceServer).StartDevice(ctx, req.(*StartDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdmService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdmServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdmService/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdmServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdmService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SdmServiceServer).Subscribe(m, &sdmServiceSubscribeServer{stream})
}

type SdmService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type sdmServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *sdmServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SdmService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdmServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdmService/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdmServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdmService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SdmServiceServer).Listen(m, &sdmServiceListenServer{stream})
}

type SdmService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type sdmServiceListenServer struct {
	grpc.ServerStream
}

func (x *sdmServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SdmService_StopDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdmServiceServer).StopDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdmService/StopDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdmServiceServer).StopDevice(ctx, req.(*StopDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SdmService_ServiceDesc is the grpc.ServiceDesc for SdmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SdmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SdmService",
	HandlerType: (*SdmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousDevice",
			Handler:    _SdmService_StartFromPreviousDevice_Handler,
		},
		{
			MethodName: "StartDevice",
			Handler:    _SdmService_StartDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _SdmService_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _SdmService_GetDevice_Handler,
		},
		{
			MethodName: "StopDevice",
			Handler:    _SdmService_StopDevice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalDevice",
			Handler:       _SdmService_StartLocalDevice_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _SdmService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _SdmService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdm.proto",
}
